export const AUTHENTICATED = "AUTHENTICATED";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const UNSET_ERROR_MESSAGE = "UNSET_ERROR_MESSAGE";